### ISSUE TITLE
CNTK deprecated

### ISSUE THREAD

**Issue by diveflo** [pg020196/Neural-Network-Translator#139]
Hi,

it looks like Microsoft basically deprecated CNTK with their [last release](https://docs.microsoft.com/en-us/cognitive-toolkit/releasenotes/cntk_2_7_release_notes).
Hence, I'd suggest we remove it from the repository to remove some of the clutter?

Let me know what you think:)

**Comment by pg020196** [comment]
Hi @diveflo,
yes, I agree. I'll look into it and remove the cntk-related items. 
Thank you for helping to keep the repository up to date!
